#!/bin/sh
# export DEBUG=true

export NVIM_APPNAME="mvim"

# export XDG_CONFIG_HOME="$HOME/.config"
# export XDG_DATA_HOME="$HOME/.local/share"
# export XDG_CACHE_HOME="$HOME/.cache"

NVIM_APPNAME="$NVIM_APPNAME" nvim "$@"

