#!/bin/sh
export DEBUG=true

export NVIM_APPNAME="mvim"
export XDG_CONFIG_HOME="$HOME/.config"
export XDG_DATA_HOME="$HOME/.local/share"
export XDG_CACHE_HOME="$HOME/.cache"

NVIM_APPNAME="$NVIM_APPNAME" nvim

#====================================================================
# export MY_NVIM="mvim"
# export MY_CONFIG_DIR="$HOME/.config/$MY_NVIM"
# export MY_RUNTIME_DIR="$HOME/.local/share/$MY_NVIM"

# export XDG_CONFIG_HOME="$HOME/.config/$MY_NVIM"
# export XDG_DATA_HOME="$HOME/.local/share/$MY_NVIM"
# export XDG_CACHE_HOME="$HOME/.cache/$MY_NVIM"

# exec nvim -u "$MY_CONFIG_DIR/init.lua" --cmd "luafile $MY_CONFIG_DIR/lua/setup-runtime-env.lua" "$@"

# exec nvim -u "$MY_CONFIG_DIR/init.lua" \
#          --cmd "let &packpath = '$MY_RUNTIME_DIR/packpath'" \
#          --cmd "luafile $MY_CONFIG_DIR/lua/setup-runtime-env.lua" \
#          "$@"

# exec env XDG_DATA_HOME="$XDG_DATA_HOME" \
# 	       XDG_CACHE_HOME="$XDG_CACHE_HOME" \
# 		     XDG_CONFIG_HOME="$XDG_CONFIG_HOME" \
# 		 nvim -u "$XDG_CONFIG_HOME/init.lua" \
#           --cmd "let &packpath = '$XDG_DATA_HOME/packpath'" \
#           --cmd "luafile $XDG_CONFIG_HOME/lua/setup-runtime-env.lua" \
# 					"$@"
